#!/usr/bin/env sh

case "$1" in
*"password for"*) msg="System" ;;
*) msg="${1:-System}" ;;
esac

printf '' | rofi -dmenu -p "Password" -password -no-fixed-num-lines -mesg "<b><span foreground='#e78284'>$msg</span></b> requesting administrative privilege"
