#!/bin/sh
case "$1" in
*"password for"*) msg="System" ;;
*) msg="${1:-System}" ;;
esac

printf '' | rofi -dmenu -p "Password" -password -no-fixed-num-lines -mesg "$msg requesting administrative privilege"
