preload = /home/huedeane/.config/nixos/home/resources/wallpaper.png

wallpaper {
    monitor = 
    path = /home/huedeane/.config/nixos/home/resources/wallpaper.png
    fit_mode = cover
}

ipc = on
splash = false
