#!/usr/bin/env sh

id=$(notify-send "NixOS" "Building configuration..." --urgency=normal --expire-time=0 --print-id)

output=$(SUDO_PROMPT="NixOS" sudo -A nixos-rebuild switch --flake "$NIXOS_CONFIG#$NIXOS_HOST" 2>&1)

if [ $? -eq 0 ]; then
  notify-send "NixOS" "Build successful" \
    --urgency=low \
    --replace-id=$id \
    --action="view=View Output"
else
  notify-send "NixOS" "Build failed" \
    --urgency=critical \
    --replace-id=$id \
    --action="view=View Output" \
    --expire-time = 60
fi | while read -r action; do
  if [ "$action" = "view" ]; then
    echo "$output" | rofi -dmenu -p "Build Output" -no-fixed-num-lines
  fi
done
